version: '3.4'

services: 
  
  products-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
  
  basket-db:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/apps/redis:/data
  
  ordering-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/ordering/data:/var/opt/mssql/data
      - ~/apps/mssql/ordering/log:/var/opt/mssql/log
      - ~/apps/mssql/ordering/secrets:/var/opt/mssql/secrets
    environment:
      MSSQL_SA_PASSWORD: "myStrong(!)Password"
      ACCEPT_EULA: "Y"
      
  identity-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    ports:
      - "1432:1433"
    volumes:
      - ~/apps/mssql/identity/data:/var/opt/mssql/data
      - ~/apps/mssql/identity/log:/var/opt/mssql/log
      - ~/apps/mssql/identity/secrets:/var/opt/mssql/secrets
    environment:
      MSSQL_SA_PASSWORD: "myStrong(!)Password"
      ACCEPT_EULA: "Y"
      
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
  
  nats:
    image: nats:2.10.11
    ports:
      - "4222:4222"