version: '3.4'

services: 
  
  products-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
  
  basket-db:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/apps/redis:/data
  
  ordering-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/opt/mssql/data
      - ~/apps/mssql/log:/var/opt/mssql/log
      - ~/apps/mssql/secrets:/var/opt/mssql/secrets
    environment:
      MSSQL_SA_PASSWORD: "myStrong(!)Password"
      ACCEPT_EULA: "Y"