version: '3.4'

services: 
  
  products-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
  
  basket-db:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/apps/redis:/data