version: '3.4'

services: 
  
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
  
  basket-db:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ~/docker/redis:/data
      
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
  
  nats:
    image: nats:2.10.11
    ports:
      - "4222:4222"